version: '3.8'

services:
  database:
    container_name: database_backend
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '4306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - app-network

  php:
    container_name: php_backend
    environment:
      - PHP_IDE_CONFIG=serverName=XdebugServer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    container_name: nginx_backend
    image: nginx:stable-alpine
    ports:
      - '8002:8002'
    volumes:
      - ./backend:/var/www/backend
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge